[package]
name = "Assignment4"
version = "0.1.0"
authors = ["HINA KHADIM"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"
text_io="0.1.7"
